(* Generated by Mirage (Wed, 1 Apr 2015 13:20:22 GMT). *)

open Lwt

let _ = Printexc.record_backtrace true

module Console = Console_unix

let console1 () =
  Console.connect "0"

module M3 = Torrent_parser.Main(Console)

let t3 = console1

let block1 () =
  Block.connect "/home/rockinbobo/lmd/master/pstl/disk.img"

module Fat1 = Fat.Fs.Make(Block)(Io_page)

let fat1 () =
  block1 () >>= function
  | `Error _ -> fail (Failure "fat1")
  | `Ok dev  -> Fat1.connect dev

module M2 = Torrent_parser.Main(Console)(Fat1)

let t2 () =
  console1 () >>= function
  | `Error e -> fail (Failure "console1")
  | `Ok console1 ->
  fat1 () >>= function
  | `Error e -> fail (Failure "fat1")
  | `Ok fat1 ->
  return (`Ok (console1, fat1))

let clock () = return (`Ok ())

let net_tap0 () =
  Netif.connect "tap0"

let random () = return (`Ok ())

module Stackv41 = struct
  module E = Ethif.Make(Netif)
  module I = Ipv4.Make(E)
  module U = Udp.Make(I)
  module T = Tcp.Flow.Make(I)(OS.Time)(Clock)(Random)
  module S = Tcpip_stack_direct.Make(Console)(OS.Time)(Random)(Netif)(E)(I)(U)(T)
  include S
end

let stackv41 () =
  console1 () >>= function
  | `Error _    -> fail (Failure "console1")
  | `Ok console ->
  net_tap0 () >>= function
  | `Error e      ->
    fail (Failure (Mirage_runtime.string_of_network_init_error "net_tap0" e))
  | `Ok interface ->
  let config = {
    V1_LWT.name = "stackv41";
    console; interface;
    mode = `IPv4 (Ipaddr.V4.of_string_exn "10.0.0.2", Ipaddr.V4.of_string_exn "255.255.255.0", [Ipaddr.V4.of_string_exn "10.0.0.1"]);
  } in
  Stackv41.connect config

module Vchan1 = Conduit_localhost

let vchan1 = Vchan1.register "localhost"

module Conduit1 = Conduit_mirage.Make(Stackv41)(Vchan1)

let conduit1 () =
  stackv41 () >>= function
  | `Error _  -> fail (Failure "stackv41")
  | `Ok stackv41 ->
  vchan1 >>= fun vchan1 ->
  Conduit1.init ~peer:vchan1 ~stack:stackv41 () >>= fun conduit1 ->
  return (`Ok conduit1)

module M1 = Torrent_parser.Main(Console)(Fat1)(Conduit1)

let t1 () =
  conduit1 () >>= function
  | `Error e -> fail (Failure "conduit1")
  | `Ok conduit1 ->
  console1 () >>= function
  | `Error e -> fail (Failure "console1")
  | `Ok console1 ->
  fat1 () >>= function
  | `Error e -> fail (Failure "fat1")
  | `Ok fat1 ->
  M1.start console1 fat1 conduit1

let () =
  OS.Main.run (join [t1 ()])
