# Generated by Mirage (Wed, 11 Mar 2015 17:58:29 GMT).

LIBS   = -pkgs lwt.syntax,mirage-block-unix,mirage-console.unix,mirage-types.lwt
PKGS   = mirage-block-unix mirage-console mirage-unix
SYNTAX = -tags "syntax(camlp4o),annot,bin_annot,strict_sequence,principal"

SYNTAX += -tag-line "<static*.*>: -syntax(camlp4o)"

FLAGS  = -cflag -g -lflags -g,-linkpkg

BUILD  = ocamlbuild -classic-display -use-ocamlfind $(LIBS) $(SYNTAX) $(FLAGS)
OPAM   = opam

export PKG_CONFIG_PATH=$(shell opam config var prefix)/lib/pkgconfig

export OPAMVERBOSE=1
export OPAMYES=1

.PHONY: all depend clean build main.native
all: build

depend:
	$(OPAM) install $(PKGS) --verbose

main.native:
	$(BUILD) main.native

main.native.o:
	$(BUILD) main.native.o

build: main.native
	ln -nfs _build/main.native mir-main

run: build
	$(SUDO) ./mir-main

clean:
	ocamlbuild -clean
