(* Generated by Mirage (Fri, 27 Feb 2015 14:32:32 GMT). *)

open Lwt

let _ = Printexc.record_backtrace true

module Console = Console_unix

let console1 () =
  Console.connect "0"

module M1 = Foo.Main(Console)

let t1 () =
  console1 () >>= function
  | `Error e -> fail (Failure "console1")
  | `Ok console1 ->
  M1.start console1

let () =
  OS.Main.run (join [t1 ()])
